"""
Custom Password Hasher with Pepper Support
This adds an extra layer of security by combining a secret pepper key with the password
before hashing. The pepper is stored separately from the database.
"""

import hashlib
from django.contrib.auth.hashers import BCryptSHA256PasswordHasher
from django.conf import settings
from django.utils.crypto import constant_time_compare


class PepperedBCryptSHA256PasswordHasher(BCryptSHA256PasswordHasher):
    """
    BCrypt hasher with pepper support.
    
    Pepper is a secret key that is added to all passwords before hashing.
    Unlike salt (which is unique per password), pepper is the same for all passwords
    and is stored in settings/environment variables, not in the database.
    
    Security benefits:
    - If database is compromised, attacker still needs the pepper key
    - Adds defense-in-depth security layer
    - Complements salting (which is still automatic with BCrypt)
    
    Note: This hasher uses a unique algorithm identifier to ensure proper verification.
    """
    
    algorithm = "bcrypt_sha256_peppered"
    
    def _add_pepper(self, password):
        """Add pepper to password"""
        pepper = getattr(settings, 'PASSWORD_PEPPER', '')
        return password + pepper
    
    def encode(self, password, salt):
        """
        Hash the password with pepper added.
        
        Args:
            password: The plain text password
            salt: Random salt (automatically generated by BCrypt)
            
        Returns:
            Hashed password string
        """
        # Add pepper to password before hashing
        peppered_password = self._add_pepper(password)
        
        # Use parent BCrypt hasher with peppered password
        return super().encode(peppered_password, salt)
    
    def verify(self, password, encoded):
        """
        Verify a password against a stored hash.
        
        Args:
            password: The plain text password to verify
            encoded: The stored hash from database
            
        Returns:
            True if password matches, False otherwise
        """
        # Add pepper to password before verification
        peppered_password = self._add_pepper(password)
        
        # Decode the stored hash to get algorithm and rest
        algorithm, rest = encoded.split('$', 1)
        
        # Use parent BCrypt verifier with peppered password
        # We need to reconstruct the hash with the parent algorithm for verification
        parent_encoded = f"bcrypt_sha256${rest}"
        return BCryptSHA256PasswordHasher().verify(peppered_password, parent_encoded)
    
    def safe_summary(self, encoded):
        """
        Return a summary of the password hash for debugging.
        Does not expose the actual hash or pepper.
        """
        summary = super().safe_summary(encoded)
        summary['pepper'] = 'enabled'
        return summary
