# Generated by Django 5.2.7 on 2025-10-30 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_name', models.CharField(max_length=100)),
                ('ct_description', models.CharField(blank=True, max_length=255)),
                ('ct_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdt_name', models.CharField(max_length=150)),
                ('pdt_mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdt_dis_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pdt_qty', models.IntegerField(default=0)),
                ('ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category')),
            ],
        ),
    ]
