# # Generated by Django 5.2.7 on 2025-10-31 12:53

# Corrected migration to use ct_id and pdt_id as primary keys
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        # --- CATEGORY MODEL ---
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),

        migrations.AlterField(
            model_name='category',
            name='ct_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),

        # --- PRODUCT MODEL ---
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),

        migrations.AlterField(
            model_name='product',
            name='pdt_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),

        migrations.AlterField(
            model_name='product',
            name='ct',
            field=models.ForeignKey(
                db_column='ct_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products',
                to='api.category'
            ),
        ),
    ]



# import django.db.models.deletion
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('api', '0001_initial'),
#     ]

#     operations = [
#         migrations.RemoveField(
#             model_name='category',
#             name='id',
#         ),
#         migrations.RemoveField(
#             model_name='product',
#             name='id',
#         ),
#         migrations.AddField(
#             model_name='category',
#             name='ct_id',
#             field=models.AutoField(primary_key=True, serialize=False),
#         ),
#         migrations.AddField(
#             model_name='product',
#             name='pdt_id',
#             field=models.AutoField(primary_key=True, serialize=False),
#         ),
#         migrations.AlterField(
#             model_name='product',
#             name='ct',
#             field=models.ForeignKey(db_column='ct_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category'),
#         ),
#         migrations.AlterModelTable(
#             name='category',
#             table='categories',
#         ),
#         migrations.AlterModelTable(
#             name='product',
#             table='products',
#         ),
#     ]
